In [1]:
import pandas as pd
from pathlib import Path


RAW_DATA_DIR = Path.cwd().parent / "data" / "raw"
DATASET_FILE = "UCI_Credit_Card.csv"

In [2]:
df = pd.read_csv(RAW_DATA_DIR / DATASET_FILE)

In [3]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [4]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [6]:
# Payment delay description
df[['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']].describe()

,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,-0.291100
std,1.123802,1.197186,1.196868,1.169139,1.133187,1.149988
min,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000

In [7]:
# Bill Statement description
df[['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6']].describe()

,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6
count,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,30000.000000
mean,51223.330900,49179.075167,4.701315e+04,43262.948967,40311.400967,38871.760400
std,73635.860576,71173.768783,6.934939e+04,64332.856134,60797.155770,59554.107537
min,-165580.000000,-69777.000000,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000
25%,3558.750000,2984.750000,2.666250e+03,2326.750000,1763.000000,1256.000000
50%,22381.500000,21200.000000,2.008850e+04,19052.000000,18104.500000,17071.000000
75%,67091.000000,64006.250000,6.016475e+04,54506.000000,50190.500000,49198.250000
max,964511.000000,983931.000000,1.664089e+06,891586.000000,927171.000000,961664.000000

In [9]:
#Previous Payment Description
df[['PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']].describe()

,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
count,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000
mean,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567
std,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775
min,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000
25%,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000
50%,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000
75%,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000
max,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000

In [8]:
df.LIMIT_BAL.describe()

count      30000.000000
mean      167484.322667
std       129747.661567
min        10000.000000
25%        50000.000000
50%       140000.000000
75%       240000.000000
max      1000000.000000
Name: LIMIT_BAL, dtype: float64

In [5]:
df.duplicated().value_counts()

False    30000
Name: count, dtype: int64

In [21]:
for cl in df.columns:
    print('*'*20+cl+'*'*20)
    print(f' min {cl}  {df[cl].min()}')
    print(f' max {cl}  {df[cl].max()}')
    print(f' type {cl}  {df[cl].dtype}')

********************ID********************
 min ID  1
 max ID  30000
 type ID  int64
********************LIMIT_BAL********************
 min LIMIT_BAL  10000.0
 max LIMIT_BAL  1000000.0
 type LIMIT_BAL  float64
********************SEX********************
 min SEX  1
 max SEX  2
 type SEX  int64
********************EDUCATION********************
 min EDUCATION  0
 max EDUCATION  6
 type EDUCATION  int64
********************MARRIAGE********************
 min MARRIAGE  0
 max MARRIAGE  3
 type MARRIAGE  int64
********************AGE********************
 min AGE  21
 max AGE  79
 type AGE  int64
********************PAY_0********************
 min PAY_0  -2
 max PAY_0  8
 type PAY_0  int64
********************PAY_2********************
 min PAY_2  -2
 max PAY_2  8
 type PAY_2  int64
********************PAY_3********************
 min PAY_3  -2
 max PAY_3  8
 type PAY_3  int64
********************PAY_4********************
 min PAY_4  -2
 max PAY_4  8
 type PAY_4  int64
********************PAY_5********************
 min PAY_5  -2
 max PAY_5  8
 type PAY_5  int64
********************PAY_6********************
 min PAY_6  -2
 max PAY_6  8
 type PAY_6  int64
********************BILL_AMT1********************
 min BILL_AMT1  -165580.0
 max BILL_AMT1  964511.0
 type BILL_AMT1  float64
********************BILL_AMT2********************
 min BILL_AMT2  -69777.0
 max BILL_AMT2  983931.0
 type BILL_AMT2  float64
********************BILL_AMT3********************
 min BILL_AMT3  -157264.0
 max BILL_AMT3  1664089.0
 type BILL_AMT3  float64
********************BILL_AMT4********************
 min BILL_AMT4  -170000.0
 max BILL_AMT4  891586.0
 type BILL_AMT4  float64
********************BILL_AMT5********************
 min BILL_AMT5  -81334.0
 max BILL_AMT5  927171.0
 type BILL_AMT5  float64
********************BILL_AMT6********************
 min BILL_AMT6  -339603.0
 max BILL_AMT6  961664.0
 type BILL_AMT6  float64
********************PAY_AMT1********************
 min PAY_AMT1  0.0
 max PAY_AMT1  873552.0
 type PAY_AMT1  float64
********************PAY_AMT2********************
 min PAY_AMT2  0.0
 max PAY_AMT2  1684259.0
 type PAY_AMT2  float64
********************PAY_AMT3********************
 min PAY_AMT3  0.0
 max PAY_AMT3  896040.0
 type PAY_AMT3  float64
********************PAY_AMT4********************
 min PAY_AMT4  0.0
 max PAY_AMT4  621000.0
 type PAY_AMT4  float64
********************PAY_AMT5********************
 min PAY_AMT5  0.0
 max PAY_AMT5  426529.0
 type PAY_AMT5  float64
********************PAY_AMT6********************
 min PAY_AMT6  0.0
 max PAY_AMT6  528666.0
 type PAY_AMT6  float64
********************default.payment.next.month********************
 min default.payment.next.month  0
 max default.payment.next.month  1
 type default.payment.next.month  int64

In [22]:
import pandas as pd
import pandera as pa
from pandera import Column, Check, DataFrameSchema

def infer_schema_from_df(df: pd.DataFrame) -> DataFrameSchema:
    columns_dict = {}

    for col in df.columns:
        dtype = df[col].dtype
        series = df[col]

        # Определяем тип Pandera по dtype pandas
        if pd.api.types.is_integer_dtype(dtype):
            pa_type = int
        elif pd.api.types.is_float_dtype(dtype):
            pa_type = float
        elif pd.api.types.is_string_dtype(dtype) or dtype == object:
            pa_type = str
        else:
            # fallback: оставляем как есть, Pandera попробует разобраться
            pa_type = dtype

        checks = []

        # nullable: если есть хотя бы один NaN — nullable=True, иначе False
        nullable = series.isna().any()

        # Для числовых добавляем min/max, если они осмысленны
        if pd.api.types.is_numeric_dtype(dtype) and not nullable:
            min_val = series.min()
            max_val = series.max()
            # Можно добавить небольшой «запас» на будущее, например ±1%
            # checks.append(Check.ge(min_val * 0.99))
            # checks.append(Check.le(max_val * 1.01))
            checks.append(Check.in_range(min_val, max_val))

        columns_dict[col] = Column(
            pa_type,
            nullable=nullable,
            checks=checks if checks else None,
        )

    return DataFrameSchema(columns_dict)


# Пример использования
# df = pd.read_csv("data.csv")  # ваш DataFrame

# Выводим статистику (как у вас в цикле)
for cl in df.columns:
    print("*" * 20 + cl + "*" * 20)
    if pd.api.types.is_numeric_dtype(df[cl]):
        print(f" min {cl}: {df[cl].min()}")
        print(f" max {cl}: {df[cl].max()}")
    print(f" type {cl}: {df[cl].dtype}")

# Генерируем схему
schema = infer_schema_from_df(df)

# Валидируем
validated_df = schema.validate(df)
print("Схема сгенерирована и валидация прошла.")

********************ID********************
 min ID: 1
 max ID: 30000
 type ID: int64
********************LIMIT_BAL********************
 min LIMIT_BAL: 10000.0
 max LIMIT_BAL: 1000000.0
 type LIMIT_BAL: float64
********************SEX********************
 min SEX: 1
 max SEX: 2
 type SEX: int64
********************EDUCATION********************
 min EDUCATION: 0
 max EDUCATION: 6
 type EDUCATION: int64
********************MARRIAGE********************
 min MARRIAGE: 0
 max MARRIAGE: 3
 type MARRIAGE: int64
********************AGE********************
 min AGE: 21
 max AGE: 79
 type AGE: int64
********************PAY_0********************
 min PAY_0: -2
 max PAY_0: 8
 type PAY_0: int64
********************PAY_2********************
 min PAY_2: -2
 max PAY_2: 8
 type PAY_2: int64
********************PAY_3********************
 min PAY_3: -2
 max PAY_3: 8
 type PAY_3: int64
********************PAY_4********************
 min PAY_4: -2
 max PAY_4: 8
 type PAY_4: int64
********************PAY_5********************
 min PAY_5: -2
 max PAY_5: 8
 type PAY_5: int64
********************PAY_6********************
 min PAY_6: -2
 max PAY_6: 8
 type PAY_6: int64
********************BILL_AMT1********************
 min BILL_AMT1: -165580.0
 max BILL_AMT1: 964511.0
 type BILL_AMT1: float64
********************BILL_AMT2********************
 min BILL_AMT2: -69777.0
 max BILL_AMT2: 983931.0
 type BILL_AMT2: float64
********************BILL_AMT3********************
 min BILL_AMT3: -157264.0
 max BILL_AMT3: 1664089.0
 type BILL_AMT3: float64
********************BILL_AMT4********************
 min BILL_AMT4: -170000.0
 max BILL_AMT4: 891586.0
 type BILL_AMT4: float64
********************BILL_AMT5********************
 min BILL_AMT5: -81334.0
 max BILL_AMT5: 927171.0
 type BILL_AMT5: float64
********************BILL_AMT6********************
 min BILL_AMT6: -339603.0
 max BILL_AMT6: 961664.0
 type BILL_AMT6: float64
********************PAY_AMT1********************
 min PAY_AMT1: 0.0
 max PAY_AMT1: 873552.0
 type PAY_AMT1: float64
********************PAY_AMT2********************
 min PAY_AMT2: 0.0
 max PAY_AMT2: 1684259.0
 type PAY_AMT2: float64
********************PAY_AMT3********************
 min PAY_AMT3: 0.0
 max PAY_AMT3: 896040.0
 type PAY_AMT3: float64
********************PAY_AMT4********************
 min PAY_AMT4: 0.0
 max PAY_AMT4: 621000.0
 type PAY_AMT4: float64
********************PAY_AMT5********************
 min PAY_AMT5: 0.0
 max PAY_AMT5: 426529.0
 type PAY_AMT5: float64
********************PAY_AMT6********************
 min PAY_AMT6: 0.0
 max PAY_AMT6: 528666.0
 type PAY_AMT6: float64
********************default.payment.next.month********************
 min default.payment.next.month: 0
 max default.payment.next.month: 1
 type default.payment.next.month: int64
Схема сгенерирована и валидация прошла.

/home/alex/Yandex.Disk/mystuff/MIFI/ml-pipeline-automation/.venv/lib/python3.13/site-packages/pandera/_pandas_deprecated.py:144: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

In [23]:
schema

<Schema DataFrameSchema(columns={'ID': <Schema Column(name=ID, type=DataType(int64))>, 'LIMIT_BAL': <Schema Column(name=LIMIT_BAL, type=DataType(float64))>, 'SEX': <Schema Column(name=SEX, type=DataType(int64))>, 'EDUCATION': <Schema Column(name=EDUCATION, type=DataType(int64))>, 'MARRIAGE': <Schema Column(name=MARRIAGE, type=DataType(int64))>, 'AGE': <Schema Column(name=AGE, type=DataType(int64))>, 'PAY_0': <Schema Column(name=PAY_0, type=DataType(int64))>, 'PAY_2': <Schema Column(name=PAY_2, type=DataType(int64))>, 'PAY_3': <Schema Column(name=PAY_3, type=DataType(int64))>, 'PAY_4': <Schema Column(name=PAY_4, type=DataType(int64))>, 'PAY_5': <Schema Column(name=PAY_5, type=DataType(int64))>, 'PAY_6': <Schema Column(name=PAY_6, type=DataType(int64))>, 'BILL_AMT1': <Schema Column(name=BILL_AMT1, type=DataType(float64))>, 'BILL_AMT2': <Schema Column(name=BILL_AMT2, type=DataType(float64))>, 'BILL_AMT3': <Schema Column(name=BILL_AMT3, type=DataType(float64))>, 'BILL_AMT4': <Schema Column(name=BILL_AMT4, type=DataType(float64))>, 'BILL_AMT5': <Schema Column(name=BILL_AMT5, type=DataType(float64))>, 'BILL_AMT6': <Schema Column(name=BILL_AMT6, type=DataType(float64))>, 'PAY_AMT1': <Schema Column(name=PAY_AMT1, type=DataType(float64))>, 'PAY_AMT2': <Schema Column(name=PAY_AMT2, type=DataType(float64))>, 'PAY_AMT3': <Schema Column(name=PAY_AMT3, type=DataType(float64))>, 'PAY_AMT4': <Schema Column(name=PAY_AMT4, type=DataType(float64))>, 'PAY_AMT5': <Schema Column(name=PAY_AMT5, type=DataType(float64))>, 'PAY_AMT6': <Schema Column(name=PAY_AMT6, type=DataType(float64))>, 'default.payment.next.month': <Schema Column(name=default.payment.next.month, type=DataType(int64))>}, checks=[], parsers=[], index=None, dtype=None, coerce=False, strict=False, name=None, ordered=False, unique=None, report_duplicates=all, unique_column_names=False, add_missing_columns=False, on_missing_columns=None, title=None, description=None, metadata=None, drop_invalid_rows=False)>

In [ ]:
df.SEX.value_counts()

SEX
2    18112
1    11888
Name: count, dtype: int64

In [30]:
df.EDUCATION.value_counts()

EDUCATION
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64

In [31]:
df.MARRIAGE.value_counts()

MARRIAGE
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

In [36]:
import pandera.pandas as pa

categorical_columns = {
    "SEX",
    "EDUCATION",
    "MARRIAGE",
    "default.payment.next.month",
}

delay_shift = {
    "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6",
}

BILLS = ['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6']

schema = pa.DataFrameSchema(
    {
        cl: pa.Column(
            dtype=df[cl].dtype,
            checks=(
                None
                if cl in BILLS
                else pa.Check.isin(df[cl].dropna().unique().tolist())
                if cl in categorical_columns
                else pa.Check.ge(-3)
                if cl in delay_shift
                else pa.Check.ge(0)
            ),
            nullable=False,
        )
        for cl in df.columns
    },
    index=pa.Index("int64", nullable=False),
    coerce=True,
    strict=False,
)

validated_df = schema.validate(df, lazy=True)

In [28]:
# Или сохранить в файл
schema.to_script("schema.py")

ImportError: Schema script formatting requires 'black' to be installed. Please install 'black' to use this feature.

In [ ]:
df['SE_MA_2'] = 0
df.loc[((df.SEX == 1) & (df.MARRIAGE == 1)) , 'SE_MA_2'] = 1 #married man
df.loc[((df.SEX == 1) & (df.MARRIAGE == 2)) , 'SE_MA_2'] = 2 #single man
df.loc[((df.SEX == 1) & (df.MARRIAGE == 3)) , 'SE_MA_2'] = 3 #divorced man
df.loc[((df.SEX == 2) & (df.MARRIAGE == 1)) , 'SE_MA_2'] = 4 #married woman
df.loc[((df.SEX == 2) & (df.MARRIAGE == 2)) , 'SE_MA_2'] = 5 #single woman
df.loc[((df.SEX == 2) & (df.MARRIAGE == 3)) , 'SE_MA_2'] = 6 #divorced woman

In [ ]:
df['AgeBin'] = 0 #creates a column of 0
df.loc[((df['AGE'] > 20) & (df['AGE'] < 30)) , 'AgeBin'] = 1
df.loc[((df['AGE'] >= 30) & (df['AGE'] < 40)) , 'AgeBin'] = 2
df.loc[((df['AGE'] >= 40) & (df['AGE'] < 50)) , 'AgeBin'] = 3
df.loc[((df['AGE'] >= 50) & (df['AGE'] < 60)) , 'AgeBin'] = 4
df.loc[((df['AGE'] >= 60) & (df['AGE'] < 70)) , 'AgeBin'] = 5
df.loc[((df['AGE'] >= 70) & (df['AGE'] < 81)) , 'AgeBin'] = 6
df.AgeBin.hist()

In [ ]:
df['Avg_exp_5'] = ((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5']))) / df['LIMIT_BAL']
df['Avg_exp_4'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4']))) / 2) / df['LIMIT_BAL']
df['Avg_exp_3'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3']))) / 3) / df['LIMIT_BAL']
df['Avg_exp_2'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3'])) +
                 (df['BILL_AMT2'] - (df['BILL_AMT3'] - df['PAY_AMT2']))) / 4) / df['LIMIT_BAL']
df['Avg_exp_1'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3'])) +
                 (df['BILL_AMT2'] - (df['BILL_AMT3'] - df['PAY_AMT2'])) +
                 (df['BILL_AMT1'] - (df['BILL_AMT2'] - df['PAY_AMT1']))) / 5) / df['LIMIT_BAL']
df[['LIMIT_BAL', 'Avg_exp_5', 'BILL_AMT5', 'Avg_exp_4', 'BILL_AMT4','Avg_exp_3', 'BILL_AMT3',
    'Avg_exp_2', 'BILL_AMT2', 'Avg_exp_1', 'BILL_AMT1', 'def_pay']].sample(20)

https://www.kaggle.com/code/lucabasa/credit-card-default-a-very-pedagogical-notebook