In [12]:
import pandas as pd
from pathlib import Path
from src.data.clean_dataset import clean_dataset
from src.data.make_dataset import load_dataset
from src.data.validation import RAW_SCHEMA, PROCESSED_SCHEMA
from src.features.build_features import build_features
from src.models.pipeline import create_pipeline


RAW_DATA_DIR = Path.cwd().parent / "data" / "raw"
DATASET_FILE = "UCI_Credit_Card.csv"

In [9]:
df = pd.read_csv(RAW_DATA_DIR / DATASET_FILE)
df = RAW_SCHEMA.validate(df, lazy=True)
df = clean_dataset(df)
df = PROCESSED_SCHEMA.validate(df, lazy=True)
print('загрузка данных успешно завершена')
df = build_features(df)
print('Дополнительные признаки сформированы')

загрузка данных успешно завершена
Дополнительные признаки сформированы

In [10]:
df.head()

   id  limit_bal  sex  education  ...  avg_exp_4  avg_exp_3  avg_exp_2  avg_exp_1
0   1    20000.0    2          2  ...   0.000000   0.011483   0.047387   0.046020
1   2   120000.0    2          2  ...   0.004213   0.003947   0.003050   0.004035
2   3    90000.0    2          2  ...   0.004344   0.003741   0.008272   0.043796
3   4    50000.0    2          2  ...   0.009360   0.154087   0.120370   0.099324
4   5    50000.0    1          2  ...   0.114980   0.242620   0.214545   0.191424

[5 rows x 32 columns]

In [11]:
df.columns

Index(['id', 'limit_bal', 'sex', 'education', 'marriage', 'age', 'pay_0',
       'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt1', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', 'pay_amt1',
       'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6', 'default',
       'se_ma_2', 'agebin', 'avg_exp_5', 'avg_exp_4', 'avg_exp_3', 'avg_exp_2',
       'avg_exp_1'],
      dtype='str')

In [18]:
df.drop(columns=['default','id'],)

       limit_bal  sex  education  ...  avg_exp_3  avg_exp_2  avg_exp_1
0        20000.0    2          2  ...   0.011483   0.047387   0.046020
1       120000.0    2          2  ...   0.003947   0.003050   0.004035
2        90000.0    2          2  ...   0.003741   0.008272   0.043796
3        50000.0    2          2  ...   0.154087   0.120370   0.099324
4        50000.0    1          2  ...   0.242620   0.214545   0.191424
...          ...  ...        ...  ...        ...        ...        ...
29995   220000.0    1          3  ...   0.311265   0.238506   0.195016
29996   150000.0    1          3  ...   0.028064   0.024135   0.021564
29997    30000.0    1          2  ...   0.128900   0.101658   0.082720
29998    80000.0    1          3  ...   0.347617   0.277850   0.236970
29999    50000.0    1          2  ...   0.252540   0.194110   0.159696

[30000 rows x 30 columns]

In [20]:
# train.py
import mlflow
from sklearn.model_selection import train_test_split

import pandas as pd

# Load data
X = df.drop(columns=['default','id'],)
y = df.default

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define features
numeric_features = ['limit_bal', 'sex', 'education', 'marriage', 'age']
categorical_features = [ 'pay_0',
       'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt1', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', 'pay_amt1',
       'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6',
       'se_ma_2', 'agebin', 'avg_exp_5', 'avg_exp_4', 'avg_exp_3', 'avg_exp_2',
       'avg_exp_1']

# Enable autologging
mlflow.sklearn.autolog()


with mlflow.start_run():
    pipeline = create_pipeline(numeric_features, categorical_features)

    # Log parameters
    mlflow.log_param("model_type", "GradientBoosting")
    mlflow.log_params(pipeline['classifier'].get_params())

    # Train model
    pipeline.fit(X_train, y_train)

    # Calculate metrics
    from sklearn.metrics import roc_auc_score, f1_score
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]
    y_pred = pipeline.predict(X_test)
    auc = roc_auc_score(y_test, y_pred_proba)
    f1 = f1_score(y_test, y_pred)

    # Log metrics
    mlflow.log_metric("test_auc", auc)
    mlflow.log_metric("test_f1", f1)

    # Log model
    mlflow.sklearn.log_model(pipeline, "model", registered_model_name="CreditDefaultModel")

    # Log artifact (feature importance plot)
    # ... code to plot feature importance ...
    # plt.savefig("feature_importance.png")
    # mlflow.log_artifact("feature_importance.png")

MlflowException: The filesystem tracking backend (e.g., './mlruns') is in maintenance mode and will not receive further updates. Please migrate to a database backend (e.g., 'sqlite:///mlflow.db') to access the latest MLflow features. The `mlflow migrate-filestore` tool migrates your existing data losslessly. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance. If the filesystem backend is required for your workflow, set `MLFLOW_ALLOW_FILE_STORE=true` to opt out of this exception.

In [ ]:
df['SE_MA_2'] = 0
df.loc[((df.SEX == 1) & (df.MARRIAGE == 1)) , 'SE_MA_2'] = 1 #married man
df.loc[((df.SEX == 1) & (df.MARRIAGE == 2)) , 'SE_MA_2'] = 2 #single man
df.loc[((df.SEX == 1) & (df.MARRIAGE == 3)) , 'SE_MA_2'] = 3 #divorced man
df.loc[((df.SEX == 2) & (df.MARRIAGE == 1)) , 'SE_MA_2'] = 4 #married woman
df.loc[((df.SEX == 2) & (df.MARRIAGE == 2)) , 'SE_MA_2'] = 5 #single woman
df.loc[((df.SEX == 2) & (df.MARRIAGE == 3)) , 'SE_MA_2'] = 6 #divorced woman

In [ ]:
df['AgeBin'] = 0 #creates a column of 0
df.loc[((df['AGE'] > 20) & (df['AGE'] < 30)) , 'AgeBin'] = 1
df.loc[((df['AGE'] >= 30) & (df['AGE'] < 40)) , 'AgeBin'] = 2
df.loc[((df['AGE'] >= 40) & (df['AGE'] < 50)) , 'AgeBin'] = 3
df.loc[((df['AGE'] >= 50) & (df['AGE'] < 60)) , 'AgeBin'] = 4
df.loc[((df['AGE'] >= 60) & (df['AGE'] < 70)) , 'AgeBin'] = 5
df.loc[((df['AGE'] >= 70) & (df['AGE'] < 81)) , 'AgeBin'] = 6
df.AgeBin.hist()

In [ ]:
df['Avg_exp_5'] = ((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5']))) / df['LIMIT_BAL']
df['Avg_exp_4'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4']))) / 2) / df['LIMIT_BAL']
df['Avg_exp_3'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3']))) / 3) / df['LIMIT_BAL']
df['Avg_exp_2'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3'])) +
                 (df['BILL_AMT2'] - (df['BILL_AMT3'] - df['PAY_AMT2']))) / 4) / df['LIMIT_BAL']
df['Avg_exp_1'] = (((df['BILL_AMT5'] - (df['BILL_AMT6'] - df['PAY_AMT5'])) +
                 (df['BILL_AMT4'] - (df['BILL_AMT5'] - df['PAY_AMT4'])) +
                 (df['BILL_AMT3'] - (df['BILL_AMT4'] - df['PAY_AMT3'])) +
                 (df['BILL_AMT2'] - (df['BILL_AMT3'] - df['PAY_AMT2'])) +
                 (df['BILL_AMT1'] - (df['BILL_AMT2'] - df['PAY_AMT1']))) / 5) / df['LIMIT_BAL']
df[['LIMIT_BAL', 'Avg_exp_5', 'BILL_AMT5', 'Avg_exp_4', 'BILL_AMT4','Avg_exp_3', 'BILL_AMT3',
    'Avg_exp_2', 'BILL_AMT2', 'Avg_exp_1', 'BILL_AMT1', 'def_pay']].sample(20)

https://www.kaggle.com/code/lucabasa/credit-card-default-a-very-pedagogical-notebook